os: linux
virt: lxd #Not a full VM - faster startup w/ some limitations
dist: bionic
language: java
jdk: openjdk8


branches:
  only:
  - main

script: "mvn clean test -Djacoco.skip=false"

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -v
